steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/yorisoi-frontend', '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=$_API_URL', '.' ]
images:
- 'gcr.io/$PROJECT_ID/yorisoi-frontend'
substitutions:
  _API_URL: 'http://localhost:8080' # Default fallback
